### PR TITLE
Server can allow folder download using REPOS_DOWNLOAD_RULE env

### PR DESCRIPTION
**Pull request by solsson**
Also fixes some response codes.

### CODE REVIEW

**Comment by solsson** [comment]
@takesson If you test this without docker, rweb reads [$_SERVER](http://php.net/reserved.variables.server) as has been done before with config so I think you can use [SetEnv](https://httpd.apache.org/docs/current/mod/mod_env.html#setenv) and [RewriteRule's E](https://httpd.apache.org/docs/current/mod/mod_rewrite.html#rewriterule) but not SetEnvIf.

**Comment by takesson** [comment]
Testing with PHP-FPM.

This works:
`RewriteRule .* - [E=REPOS_DOWNLOAD_RULE:|^/svn/[^/]+/testdir/.+|]`

This works:
`SetEnv REPOS_DOWNLOAD_RULE |^/svn/[^/]+/testdir/.+|`

**Comment by takesson** [comment]
What are the pipe characters for?

**Comment by solsson** [comment]
Great. Thanks for examples of both.

PHP deprecated the old regex form in favor of PCRE, which start and end with a delimiter. The typical delimiter is `/` but with that you have to escape every slash in the regex.

**Pull request merged**
